# Generated by Django 5.2.12 on 2026-03-07 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('E', 'Entrada'), ('S', 'Saída'), ('II', 'Início de Intervalo'), ('FI', 'Fim de Intervalo')], max_length=2)),
                ('timestamp', models.DateTimeField()),
                ('nsr', models.BigIntegerField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('foto_path', models.CharField(max_length=500)),
                ('foto_hash', models.CharField(max_length=64)),
                ('confianca_biometrica', models.FloatField()),
                ('origem', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='online', max_length=10)),
                ('sincronizado_em', models.DateTimeField(blank=True, null=True)),
                ('justificativa', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='employees.employee')),
                ('registro_original', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ajustes', to='attendance.attendancerecord')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Registro de Ponto',
                'verbose_name_plural': 'Registros de Ponto',
                'ordering': ['-timestamp', '-id'],
                'indexes': [models.Index(fields=['tenant', 'employee', 'timestamp'], name='attendance__tenant__7adaf8_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'nsr'), name='attendance_record_unique_nsr_per_tenant')],
            },
        ),
    ]
