# Generated by Django 5.2.12 on 2026-03-07 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('employees', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='client_event_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(condition=models.Q(('client_event_id__isnull', False)), fields=('tenant', 'client_event_id'), name='attendance_record_unique_client_event_id_per_tenant'),
        ),
    ]
