# Generated by Django 5.2.12 on 2026-03-11 19:16

import uuid

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_unique_owner_per_tenant'),
        ('attendance', '0002_attendancerecord_client_event_id_and_more'),
        ('employees', '0003_employee_data_admissao_employee_data_nascimento_and_more'),
        ('tenants', '0002_tenant_bairro_tenant_cep_tenant_cidade_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeClock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=80)),
                ('descricao', models.CharField(blank=True, default='', max_length=255)),
                ('tipo_relogio', models.CharField(choices=[('APLICATIVO', 'Aplicativo')], default='APLICATIVO', max_length=20)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo'), ('EM_MANUTENCAO', 'Em Manutenção')], default='ATIVO', max_length=20)),
                ('metodo_autenticacao', models.CharField(choices=[('FACIAL', 'Reconhecimento Facial')], default='FACIAL', max_length=20)),
                ('activation_code', models.CharField(db_index=True, max_length=6, unique=True)),
                ('plataforma', models.CharField(choices=[('DESCONHECIDA', 'Desconhecida'), ('WEB', 'Web'), ('ANDROID', 'Android'), ('IOS', 'iOS')], default='DESCONHECIDA', max_length=20)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_time_clocks', to=settings.AUTH_USER_MODEL)),
                ('current_device', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_clock', to='accounts.device')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Relógio de Ponto',
                'verbose_name_plural': 'Relógios de Ponto',
                'ordering': ['nome', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimeClockEmployeeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_clock_assignments', to='employees.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
                ('time_clock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_assignments', to='attendance.timeclock')),
            ],
            options={
                'verbose_name': 'Vínculo de Colaborador no Relógio',
                'verbose_name_plural': 'Vínculos de Colaboradores no Relógio',
                'ordering': ['employee__nome', 'id'],
            },
        ),
        migrations.AddField(
            model_name='timeclock',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='time_clocks', through='attendance.TimeClockEmployeeAssignment', to='employees.employee'),
        ),
        migrations.CreateModel(
            name='TimeClockGeofence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('raio_metros', models.PositiveIntegerField()),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
                ('time_clock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='geofence', to='attendance.timeclock')),
            ],
            options={
                'verbose_name': 'Cerca Virtual do Relógio',
                'verbose_name_plural': 'Cercas Virtuais dos Relógios',
            },
        ),
        migrations.AddIndex(
            model_name='timeclockemployeeassignment',
            index=models.Index(fields=['tenant', 'time_clock'], name='attendance__tenant__8590c1_idx'),
        ),
        migrations.AddIndex(
            model_name='timeclockemployeeassignment',
            index=models.Index(fields=['tenant', 'employee'], name='attendance__tenant__cf912e_idx'),
        ),
        migrations.AddConstraint(
            model_name='timeclockemployeeassignment',
            constraint=models.UniqueConstraint(fields=('tenant', 'time_clock', 'employee'), name='attendance_timeclockassignment_unique_employee_per_clock'),
        ),
        migrations.AddConstraint(
            model_name='timeclock',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nome'), models.F('tenant'), name='attendance_timeclock_unique_lower_name_per_tenant'),
        ),
    ]
