# Generated by Codex on 2026-03-15

import django.db.models.deletion
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_unique_owner_per_tenant"),
        ("attendance", "0003_timeclock_timeclockemployeeassignment_and_more"),
        ("employees", "0003_employee_data_admissao_employee_data_nascimento_and_more"),
        ("tenants", "0002_tenant_bairro_tenant_cep_tenant_cidade_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceAdjustment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("action_type", models.CharField(choices=[("ADD_MARK", "Adicionar Marcação"), ("DISREGARD_MARK", "Desconsiderar Marcação")], max_length=20)),
                ("status", models.CharField(choices=[("PENDENTE", "Pendente"), ("APROVADA", "Aprovada"), ("REJEITADA", "Rejeitada"), ("DESCONSIDERADA", "Desconsiderada")], default="PENDENTE", max_length=20)),
                ("target_date", models.DateField()),
                ("reason", models.TextField()),
                ("decision_note", models.TextField(blank=True, default="")),
                ("auto_generated", models.BooleanField(default=False)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("attendance_record", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="attendance_adjustment", to="attendance.attendancerecord")),
                ("decided_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="attendance_adjustments_decided", to="accounts.user")),
                ("employee", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="attendance_adjustments", to="employees.employee")),
                ("requested_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="attendance_adjustments_requested", to="accounts.user")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="%(app_label)s_%(class)s_set", to="tenants.tenant")),
                ("target_record", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="attendance_adjustment_targets", to="attendance.attendancerecord")),
            ],
            options={
                "verbose_name": "Ajuste de Ponto",
                "verbose_name_plural": "Ajustes de Ponto",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(fields=["tenant", "employee", "target_date"], name="attendance__tenant__416f34_idx"),
                    models.Index(fields=["tenant", "status", "target_date"], name="attendance__tenant__b9e887_idx"),
                ],
            },
        ),
    ]
