# Generated by Django 6.0.3 on 2026-03-08 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_first_name_user_last_name_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cpf',
            field=models.CharField(blank=True, db_index=True, max_length=11, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_account_owner',
            field=models.BooleanField(default=False),
        ),
    ]
