# Generated by Django 6.0.3 on 2026-03-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_cpf_user_is_account_owner"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_account_owner", True), ("tenant__isnull", False)),
                fields=("tenant",),
                name="accounts_user_unique_owner_per_tenant",
            ),
        ),
    ]
