# Generated by Django 5.2.12 on 2026-03-07 15:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Este campo deve conter exatamente 11 dígitos numéricos.', regex='^\\d{11}$')])),
                ('pis', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Este campo deve conter exatamente 11 dígitos numéricos.', regex='^\\d{11}$')])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'ordering': ['nome'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'cpf'), name='employees_employee_unique_cpf_per_tenant')],
            },
        ),
        migrations.CreateModel(
            name='NSRSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultimo_nsr', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Sequência NSR',
                'verbose_name_plural': 'Sequências NSR',
                'constraints': [models.UniqueConstraint(fields=('tenant',), name='employees_nsrsequence_unique_tenant')],
            },
        ),
    ]
