# Generated by Django 5.2.12 on 2026-03-08 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('tenants', '0002_tenant_bairro_tenant_cep_tenant_cidade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('descricao', models.CharField(blank=True, default='', max_length=255)),
                ('tipo', models.CharField(choices=[('SEMANAL', 'Semanal'), ('12X36', '12x36'), ('FRACIONADA', 'Fracionada'), ('EXTERNA', 'Externa')], max_length=10)),
                ('configuracao', models.JSONField(blank=True, default=dict)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Jornada de Trabalho',
                'verbose_name_plural': 'Jornadas de Trabalho',
                'ordering': ['nome'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('ativo', True)), fields=('tenant', 'nome'), name='employees_workschedule_unique_nome_ativo_per_tenant')],
            },
        ),
    ]
