# Generated by Django 6.0.3 on 2026-03-07 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentimentoBiometrico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('aceito', models.BooleanField(default=True)),
                ('ip_origem', models.GenericIPAddressField(blank=True, null=True)),
                ('versao_termo', models.CharField(max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consentimentos_biometricos', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Consentimento Biométrico',
                'verbose_name_plural': 'Consentimentos Biométricos',
                'ordering': ['-timestamp'],
            },
        ),
    ]
