# Generated by Django 5.2.12 on 2026-03-07 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometrics', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacialEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding_data', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facial_embeddings', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Embedding Facial',
                'verbose_name_plural': 'Embeddings Faciais',
                'ordering': ['-created_at'],
            },
        ),
    ]
