# Generated by Django 5.2.12 on 2026-03-11 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_unique_owner_per_tenant"),
        ("biometrics", "0002_facialembedding"),
        ("employees", "0003_employee_data_admissao_employee_data_nascimento_and_more"),
        ("tenants", "0002_tenant_bairro_tenant_cep_tenant_cidade_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BiometricInvite",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("channel", models.CharField(choices=[("whatsapp", "WhatsApp")], default="whatsapp", max_length=20)),
                (
                    "provider",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                ("sent_to", models.CharField(max_length=20)),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("sent", "Enviado"),
                            ("failed", "Falhou"),
                            ("used", "Utilizado"),
                            ("expired", "Expirado"),
                            ("revoked", "Revogado"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("provider_message_id", models.CharField(blank=True, default="", max_length=120)),
                ("last_error", models.CharField(blank=True, default="", max_length=255)),
                ("provider_payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="biometric_invites_created",
                        to="accounts.user",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="biometric_invites",
                        to="employees.employee",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Convite Biométrico",
                "verbose_name_plural": "Convites Biométricos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="biometricinvite",
            constraint=models.UniqueConstraint(
                fields=("tenant", "employee", "token_hash"),
                name="biometrics_biometricinvite_unique_employee_token_per_tenant",
            ),
        ),
    ]
