# Generated by Django 5.2.12 on 2026-03-13 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometrics', '0003_biometricinvite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biometricinvite',
            name='provider_message_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
